# Generated by Django 3.2.11 on 2022-01-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0007_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
