# Generated by Django 3.2.11 on 2022-02-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0009_auto_20220210_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=124),
        ),
    ]
