# Generated by Django 4.0.2 on 2022-02-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0012_discrict_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discrict',
            new_name='District',
        ),
    ]
